######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 19 01:13:09 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FieldConstants.h FieldView.h ScratchTool.h
SOURCES += FieldView.cpp main.cpp ScratchTool.cpp
