######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 18 16:04:11 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ScratchTool.h
SOURCES += main.cpp ScratchTool.cpp
