######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 18 22:39:09 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FieldConstants.h FieldView.h ScratchTool.h
SOURCES += FieldView.cpp main.cpp ScratchTool.cpp
